# Generated by Django 5.0 on 2023-12-15 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puma_storeapp', '0005_rename_pid_cart_store_pid_cart_store_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_store',
            new_name='Storecart',
        ),
    ]
