# Generated by Django 5.0 on 2023-12-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puma_storeapp', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pid',
            new_name='Pid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='uid',
            new_name='Uid',
        ),
    ]
